### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zenios** [braintree/apollo-tracing-uploader-java#5]
Hi

First of all i would like to thank you for this great library. I just installed it and works perfectly.  Find below my feedback

1. It does not work with graphql-java-14

https://github.com/braintree/apollo-tracing-uploader-java/blob/86fa1b035e12f755e5b12deb8873f46ca80c31d0/src/main/java/com/braintreepayments/apollo_tracing_uploader/TracingUploadInstrumentationState.java#L120

Due to the changes to introspection getUnwrappedNonNullType().getName is not available any more

You have to use GraphQLTypeUtil.simplePrint(stepInfo.getParent().getUnwrappedNonNullType())

2. Uploader.upload would be better to return a CompletableFuture.

I integrated your library with vertx and its asynchronous httpclient (https://vertx.io/docs/vertx-web-client/java/)  which is based on the reactive pattern. 

In order to implement shutdown correctly (ScheduledBatchingTraceProducer) i need to know when upload has completed and by returning void i cannot get than info.

Again thank you very much

**Comment by alexgenco** [comment]
Thanks for the feedback!

>     1. It does not work with graphql-java-14

Thanks, we will put this change on our list. Feel free to open a PR as well.

>     1. Uploader.upload would be better to return a CompletableFuture.

Would you mind posting an example of how you envision the `CompletableFuture` linking together the scheduled producer and the uploader? I think I like this change, just want to make sure I understand the use case.

**Comment by alexgenco** [comment]
@zenios FYI we just published 0.1.0, and it includes the graphql-java 14.0 update.

**Comment by zenios** [comment]
Great will check tomorrow and let you know what is missing in order to replace my fork with upstream

Thanks again

**Comment by alexgenco** [comment]
Resolved by https://github.com/braintree/apollo-tracing-uploader-java/pull/10
